# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kaleb/Documents/Linked-List

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kaleb/Documents/Linked-List

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kaleb/Documents/Linked-List/CMakeFiles /home/kaleb/Documents/Linked-List/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kaleb/Documents/Linked-List/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tester

# Build rule for target.
tester: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tester
.PHONY : tester

# fast build rule for target.
tester/fast:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/build
.PHONY : tester/fast

#=============================================================================
# Target rules for targets named linked-list

# Build rule for target.
linked-list: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 linked-list
.PHONY : linked-list

# fast build rule for target.
linked-list/fast:
	$(MAKE) -f Linked-List/CMakeFiles/linked-list.dir/build.make Linked-List/CMakeFiles/linked-list.dir/build
.PHONY : linked-list/fast

Tests/test.o: Tests/test.cpp.o

.PHONY : Tests/test.o

# target to build an object file
Tests/test.cpp.o:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/Tests/test.cpp.o
.PHONY : Tests/test.cpp.o

Tests/test.i: Tests/test.cpp.i

.PHONY : Tests/test.i

# target to preprocess a source file
Tests/test.cpp.i:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/Tests/test.cpp.i
.PHONY : Tests/test.cpp.i

Tests/test.s: Tests/test.cpp.s

.PHONY : Tests/test.s

# target to generate assembly for a file
Tests/test.cpp.s:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/Tests/test.cpp.s
.PHONY : Tests/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... tester"
	@echo "... linked-list"
	@echo "... Tests/test.o"
	@echo "... Tests/test.i"
	@echo "... Tests/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

